### ISSUE TITLE
base on ubuntu:14.04

### ISSUE THREAD

**Issue by bgruening** [bgruening/docker-ipython-notebook#26]
I will spend some time to merge @jmchilton PR finally and update the image in general. 
Do we want to base this Image on ubuntu:14.04?

Pro: Galaxy is also using it and we could save some space on disc if this layer is the same.
Con: Ubuntu is in general a larger Image than Debian ... 

I will test this next week in production on a workshop with this Image: https://github.com/bgruening/docker-recipes/tree/master/ipython-notebook-plus

Comments welcome!

**Comment by erasche** [comment]
Hmmm, if Galaxy is using it for their image, it would make sense to do the same. Probably anyone using docker seriously can spare the extra couple of gigs for another image, I don't think we need to worry about size too much? Anyway, I'm in favour of it.

Nice that you've got a "plus" version already! I'll try and invest some time in figuring out how "notebook image selection" might work soon :)

**Comment by bgruening** [comment]
`:dev` is now based on ubuntu:14:04. We have a nice DIO now and versioned Docker builds. If something broke you can use `bgruening/docker-ipython-notebook:0.2`.

**Comment by erasche** [comment]
excellent, tagged images! Definitely on the way to selectable image launching :D
