### ISSUE TITLE
Dynamically resolve ``$DOCKER_HOST``...

### ISSUE THREAD

**Issue by jmchilton** [bgruening/docker-ipython-notebook#31]
Dynamically resolve ``$DOCKER_HOST``  if it appears in ``galaxy_url``. 

Use ``netstat`` value plus [this idiom](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config.py#L370).

**Comment by erasche** [comment]
Just for clarity, you intend to pass `galaxy_url = http://$DOCKER_HOST:8080/galaxy` (or similar) and then have `galaxy.py` resolve that?

**Comment by jmchilton** [comment]
Exactly.

**Comment by erasche** [comment]
Yeah, I'd +1 that.

**Comment by bgruening** [comment]
Sounds good to me! Still catching up with all the mails.
