### ISSUE TITLE
Test for group creation, but not user creation

### ISSUE THREAD

**Issue by erasche** [bgruening/docker-ipython-notebook#47]
In https://github.com/bgruening/docker-ipython-notebook/commit/ea2a92df12049cf5926d043c875f835103665bed it's mentioned that the host folder GID was in use by the docker image. Would it not be unreasonable to think that the host folder UID might also already exist in the system?

**Comment by bgruening** [comment]
Users are always above 1000 isn't it? In this container we do not have any other user over 1000. At least this was my thinking. &#x1f60a;

**Comment by erasche** [comment]
I was thinking of the case where the admin has set the galaxy user on the host as a system user, thus with an ID < 1000.

**Comment by erasche** [comment]
If, like most of us, galaxy is a regular user, then it would be just fine.

**Comment by hexylena** [comment]
No one has reported issues with this, so closing the old issue.
