### ISSUE TITLE
Kernels requested for Jupyter Galaxy IE

### ISSUE THREAD

**Issue by erasche** [bgruening/docker-ipython-notebook#53]
If you comment on this issue, voting for languages, I'll delete your comment and adjust the tallies accordingly. :)

Implemented | Language | Votes
--- | --- | ---
 | Python | 3
 | R | 3
 | Perl | 1
 | Ruby | 1
 | Julia | 1

**Comment by nitesh1989** [comment]
Python, R.

**Comment by natefoo** [comment]
[MUMPS](https://en.wikipedia.org/wiki/MUMPS)

**Comment by erasche** [comment]
BF `:P`

**Comment by nitesh1989** [comment]
```
++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.
```
