### ISSUE TITLE
add pyvcf

### ISSUE THREAD

**Issue by tiagoantao** [bgruening/docker-ipython-notebook#57]
Hi,

I am wondering if pyvcf could be added to the docker file?

Thanks

**Comment by erasche** [comment]
Added to #56

**Comment by erasche** [comment]
If the package doesn't get added, I highly recommend creating your own flavour of the notebook, it's really easy to do:

```dockerfile
FROM bgruening/docker-ipython-notebook:latest
RUN pip install pyvcf
```

**Comment by tiagoantao** [comment]
I know, but considering that this such a common package, I just though
about suggesting it...

On 1 September 2015 at 17:28, Eric Rasche <notifications@github.com> wrote:

> If the package doesn't get added, I highly recommend creating your own
> flavour of the notebook, it's really easy to do:
>
> FROM bgruening/docker-ipython-notebook:latestRUN pip install pyvcf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bgruening/docker-ipython-notebook/issues/57#issuecomment-136890807>
> .
>



-- 
"Democracy matters more than any currency arrangement." - Paul Krugman

**Comment by bgruening** [comment]
I will look at the dependencies for this package and if they are not so large I will add it in the next version.
Thanks!
